módulo fetchmail_attach_from_folder para la 15
aurestic/server-tools pull request #10
Opened 2023-03-22 11:05 UTC by almumu

2023-03-22 11:12 UTC, zamberjo requested changes
las traducciones dan error al actualizar, supongo que pasará también en la 14.0 puedes arreglarlo en ambos?
```
2023-03-22 11:11:15,626 1 ERROR zambu_testaures15_aurestic odoo.sql_db: bad query:  INSERT INTO ir_translation(name, lang, res_id, src, type, value, module, state, comments)
                           SELECT name, lang, res_id, src, type, value, module, state, comments
                           FROM tmp_ir_translation_import
                           WHERE type = 'model'
                           AND noupdate IS NOT TRUE
                           ON CONFLICT (type, lang, name, res_id) WHERE type = 'model'
                            DO UPDATE SET (name, lang, res_id, src, type, value, module, state, comments) = (EXCLUDED.name, EXCLUDED.lang, EXCLUDED.res_id, EXCLUDED.src, EXCLUDED.type, EXCLUDED.value, EXCLUDED.module, EXCLUDED.state, EXCLUDED.comments)
                            WHERE EXCLUDED.value IS NOT NULL AND EXCLUDED.value != '';
                       
ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
 
2023-03-22 11:11:15,627 1 WARNING zambu_testaures15_aurestic odoo.modules.loading: Transient module states were reset 
2023-03-22 11:11:15,627 1 ERROR zambu_testaures15_aurestic odoo.modules.registry: Failed to load registry 
2023-03-22 11:11:15,627 1 CRITICAL zambu_testaures15_aurestic odoo.service.server: Failed to initialize database `zambu_testaures15_aurestic`. 
Traceback (most recent call last):
  File "/opt/odoo/custom/src/repos/odoo/odoo/service/server.py", line 1260, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/custom/src/repos/odoo/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo/custom/src/repos/odoo/odoo/modules/loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/custom/src/repos/odoo/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/custom/src/repos/odoo/odoo/modules/loading.py", line 231, in load_module_graph
    module._update_translations(overwrite=overwrite)
  File "/opt/odoo/custom/src/repos/odoo/odoo/addons/base/models/ir_module.py", line 945, in _update_translations
    self.env['ir.translation']._load_module_terms(mod_names, filter_lang, overwrite)
  File "/opt/odoo/custom/src/repos/odoo/odoo/addons/base/models/ir_translation.py", line 826, in _load_module_terms
    tools.trans_load(self._cr, trans_file, lang, verbose=False, overwrite=lang_overwrite)
  File "/opt/odoo/custom/src/repos/odoo/odoo/tools/translate.py", line 1159, in trans_load
    return trans_load_data(cr, fileobj, fileformat, lang,
  File "/opt/odoo/custom/src/repos/odoo/odoo/tools/translate.py", line 1222, in trans_load_data
    irt_cursor.finish()
  File "/opt/odoo/custom/src/repos/odoo/odoo/addons/base/models/ir_translation.py", line 110, in finish
    cr.execute(""" INSERT INTO %s(name, lang, res_id, src, type, value, module, state, comments)
  File "<decorator-gen-3>", line 2, in execute
  File "/opt/odoo/custom/src/repos/odoo/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo/custom/src/repos/odoo/odoo/sql_db.py", line 311, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.CardinalityViolation: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
```

2023-03-24 07:17 UTC, zamberjo approved these changes

2023-03-24 07:53 UTC, carlosbej2 approved these changes

2023-03-24 08:02 UTC, JordiToledo approved these changes

2023-03-24 08:27 UTC, merged