11.0 mig base_multi_image
aurestic/server-tools pull request #4
Opened 2020-09-15 06:52 UTC by P4R

Migramos el modulo base_multi_image

2020-09-15 10:27 UTC, zamberjo requested changes

2020-09-15 10:27 UTC, zamberjo commented on base_multi_image/__init__.py
> +# -*- coding: utf-8 -*-
Sobra
```suggestion
```

2020-09-15 10:27 UTC, zamberjo commented on base_multi_image/__manifest__.py
> +# -*- coding: utf-8 -*-
```suggestion
```

2020-09-15 10:27 UTC, zamberjo commented on base_multi_image/__manifest__.py
> +    "version": "11.0.0.0.0",
```suggestion
    "version": "11.0.1.0.0",
```

2020-09-15 10:27 UTC, zamberjo commented on base_multi_image/hooks.py
> +# -*- coding: utf-8 -*-
```suggestion
```

2020-09-15 10:27 UTC, zamberjo commented on base_multi_image/hooks.py
> +import logging
```suggestion
import logging

from odoo import api, SUPERUSER_ID
```

2020-09-24 08:56 UTC, zamberjo requested changes
?

2020-09-24 09:00 UTC, P4R commented
> ?

Ahora sí que está :sweat_smile:

2020-09-24 10:58 UTC, zamberjo approved these changes

2020-10-01 06:44 UTC, almumu approved these changes

2020-10-01 06:45 UTC, merged