Task#99914
aurestic/server-tools pull request #8
Opened 2022-07-13 11:25 UTC by zamberjo

[MIG] fetchmail_attach_from_folder from 11.0

2022-07-13 12:58 UTC, almumu requested changes

2022-07-13 12:58 UTC, almumu commented on fetchmail_attach_from_folder/models/fetchmail_server.py
> +    server_type = fields.Selection(default="imap")
sin selection?

2022-07-13 13:00 UTC, almumu approved these changes
supongo que no es nuestro el módulo y lo has migrado tal cual, porque con los "for this in self" me duelen los ojos XD

2022-07-13 14:36 UTC, JordiToledo approved these changes

2022-07-14 06:00 UTC, carlosbej2 approved these changes

2022-07-14 06:15 UTC, merged

2022-07-14 06:15 UTC, zamberjo commented
> supongo que no es nuestro el módulo y lo has migrado tal cual, porque con los "for this in self" me duelen los ojos XD

Crees bien